# Generated by Django 4.2 on 2023-04-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MESapp", "0003_alter_userprofile_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
