# Generated by Django 4.2 on 2023-04-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MESapp", "0004_alter_userprofile_is_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
