# Generated by Django 4.2 on 2023-04-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MESapp", "0005_person"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="person",
            table="mesapp_person",
        ),
    ]
