# Generated by Django 4.2 on 2023-04-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MESapp", "0006_alter_person_options_alter_person_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="SewingEfficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sc", models.IntegerField(blank=True)),
                ("style", models.CharField(blank=True, max_length=255)),
                ("buyer", models.CharField(blank=True, max_length=255)),
                (
                    "smv",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=10),
                ),
                (
                    "working_hrs",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("line_balance_count", models.CharField(blank=True, max_length=255)),
                (
                    "othrs",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=10),
                ),
                (
                    "produce_mins",
                    models.DecimalField(
                        blank=True, decimal_places=10, default="", max_digits=10
                    ),
                ),
                (
                    "use_mins",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=10),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("create_date", models.CharField(blank=True, max_length=255)),
                ("line_no", models.CharField(blank=True, max_length=255)),
                (
                    "actual_efficiency",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=10),
                ),
                (
                    "planned_efficiency",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=10),
                ),
                ("pqty", models.IntegerField(blank=True)),
                ("component", models.CharField(blank=True, max_length=255)),
                ("plan_qty", models.CharField(blank=True, max_length=255)),
                ("plan_smv", models.CharField(blank=True, max_length=255)),
                (
                    "plan_efficiency",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=10),
                ),
                ("sec_id", models.CharField(blank=True, max_length=255)),
                ("shift", models.CharField(blank=True, max_length=255)),
                ("date_time", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.CharField(blank=True, max_length=255)),
                (
                    "ordertype",
                    models.CharField(blank=True, db_column="orderType", max_length=255),
                ),
                ("aql_fail", models.CharField(blank=True, max_length=255)),
                ("cni_fail", models.CharField(blank=True, max_length=255)),
                ("prod_day", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
