# Generated by Django 4.2 on 2023-04-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MESapp", "0007_sewingefficiency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sewingefficiency",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="sewingefficiency",
            table="Sewing_Efficiency",
        ),
    ]
